spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userDB?autoReconnect=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 10000
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
  jackson:
    serialization:
      WRITE_DATES_WITH_ZONE_ID: true
  mvc:
    throw-exception-if-no-handler-found: true
    path match:
      matching-strategy: ant_path_matcher
  web:
    resources:
      add-mappings: false
server:
  port: 8080
  servlet:
    context-path: /ionix/user-api
logging:
  level:
    cl.ionix: debug

path-services-balancer: ${PATH_SERVICES_BALANCER:#{null}}